"""Compile v2b raw parity, parent-run commands, and source-audit boundaries."""
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path

root=Path('D:/ai/projects/sera/research-continuation/12_reproductions/bundle2')
out=root.parents[1]/'01_audit'
source=root/'source'
parity=json.loads((root/'independent-audit/parity.json').read_text())
archive=Path('C:/Users/admin/Downloads/SERA_Kavi_Astra_Research_Pack_v2b.zip')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
canonical=lambda d:json.dumps(d,sort_keys=True,separators=(',',':'),allow_nan=False)
digest=lambda d:hashlib.sha256(canonical(d).encode()).hexdigest()
assert sha(archive)=='4e9b829f67aca7bbb543b0c03eff022b019b67698a0f27f899fbd7a8186e814f'
release=json.loads((source/'RELEASE.json').read_text())
code_map={f'code/{k}':v for k,v in parity['all_code_posix_map'].items()}
states={name:json.loads((root/name/'state.json').read_text()) for name in ('verification','reproduction')}
jobs={name:[{k:v for k,v in j.items() if k!='outputs'}|{'output_count':len(j.get('outputs',{}))} for j in state['jobs']] for name,state in states.items()}
claims=[
 {'id':'B2-01','label':'D. NEWLY-EXECUTED','claim':'Original second archive hash verified; all 726 package manifest entries match unchanged source. Its embedded first archive has the exact original first-bundle identity.','evidence':['independent-audit/parity.json','source/baseline/IDENTITY.json']},
 {'id':'B2-02','label':'D. NEWLY-EXECUTED','claim':'55 package unit tests pass. Original verify-mode archive replay fails native source identity; portable path serialization computes the archived identity from unchanged bytes and replays 1050 evaluations, 240 teaching artifacts and 50 generation snapshots.','evidence':['verification/state.json','portable-verification/identity.json','portable-verification/replay.json']},
 {'id':'B2-03','label':'D. NEWLY-EXECUTED','claim':'Fresh full reproduction completed 7 jobs under a 600-second cumulative cap, with intentional max-jobs pause/resume; 250 main trials, 10 lifetimes and 100 paired repairs generated, then both fresh replay verifiers pass.','evidence':['reproduction/state.json','reproduction/evidence/replay.json','reproduction/evidence/repair_replay.json'],'boundary':'Same registered seeds; not additional independent scientific replications.'},
 {'id':'B2-04','label':'D. NEWLY-EXECUTED','claim':'Archived-versus-fresh comparison is not completely within the original atol=rtol=1e-12: 2 float leaves fail in main_106_misspecified_frozen; 99 fail in 219_sine_4. Every meta numeric leaf passes, and all discrete decisions/selections match.','evidence':['independent-audit/parity.json'],'boundary':'Do not replace archived strict-verifier failure by the fresh self-replay pass.'},
 {'id':'B2-05','label':'D. NEWLY-EXECUTED','claim':'P2 archived strict replay fails an exact parent coefficient hash. Across all 100 repair records 300 hash fields and 77 deployed JSON byte counts differ; numeric differences are separately retained, not ignored.','evidence':['portable-verification/repair_failure.json','independent-audit/parity.json'],'boundary':'Failure record is explicitly a transcription of the execution-tool exception, not captured raw stderr.'},
 {'id':'B2-06','labels':['C. PREVIOUSLY-EXECUTED','D. NEWLY-EXECUTED'],'claim':'Active dense reduces in-basis interpolation MSE from 0.000450703 (random dense) to 0.000229922; sparse active does not establish an accuracy advantage.','evidence':['reproduction/results/paired_comparisons.json','independent-audit/parity.json'],'boundary':'Supplied six-feature language, direct reset probes, known noise, and descriptive ten-seed cluster intervals.'},
 {'id':'B2-07','labels':['C. PREVIOUSLY-EXECUTED','D. NEWLY-EXECUTED'],'claim':'Misspecified active dense nominal 95% coverage is only 21.2890625%; parameter covariance fails to account for omitted mechanisms.','evidence':['independent-audit/parity.json','reproduction/results/main']},
 {'id':'B2-08','labels':['C. PREVIOUSLY-EXECUTED','D. NEWLY-EXECUTED'],'claim':'Generation-four policy-only and policy-with-retained-knowledge intervals include zero; retained-knowledge policy point estimate is worse. No robust learning-procedure improvement is established.','evidence':['reproduction/results/meta_paired_comparisons.json','independent-audit/parity.json']},
 {'id':'B2-09','labels':['C. PREVIOUSLY-EXECUTED','D. NEWLY-EXECUTED'],'claim':'P2 reproduces the same choices: sine_4 accepted 20/20 but correct frequency only 6/20; sine_6 accepted and identified 20/20; sine_2 and sine_2.5 never trigger.','evidence':['independent-audit/parity.json'],'boundary':'Finite supplied integer sine grammar, fitted observed buffer, separate empirical qualification, no general representation discovery.'},
 {'id':'B2-10','label':'A. SOURCE-OBSERVED','claim':'Original snapshot alias and runner-accounting defects are preserved with initial records; canonical study uses repaired ownership source. Current replay checks historical link consistency but does not establish all hostile-process or source-completeness guarantees.','evidence':['source/evidence/snapshot_failure.json','source/evidence/orchestrator_failure.json','source/tests/test_snapshot_ownership.py','source/code/verify_results.py']},
 {'id':'B2-11','label':'G. PROPOSED','claim':'Common SERA/Kavi owner, learned applicability, latent migration, arbitrary program synthesis, and broad learning-policy transfer remain integration targets, not achievements of this analytic harness.','evidence':['source/docs/ARCHITECTURE_AND_FINDINGS.md','source/WORKPLAN.json']}
]
limitations=[
 {'file':'code/run_study.py','finding':'source_identity uses native str(relative_path), producing different digests from identical bytes on Windows versus POSIX; the portable wrapper repairs serialization only.'},
 {'file':'code/verify_results.py','finding':'Checks source digest and record digest, but no explicit expected record set/count or protocol_sha256 check. An incomplete or empty glob can receive PASS. This audit independently verifies all expected file sets and all 360 record protocol digests.'},
 {'file':'code/verify_repair.py','finding':'Same incomplete/empty-glob weakness; runner_sha256 pins only run_repair.py, excluding imported features/digest/namespace implementations and explicit protocol identity. Package manifest supplies broader source integrity in this audit.'},
 {'file':'code/verify_results.py','finding':'Posterior restore checks the mean/covariance implied by stored sufficient statistics; the verifier does not independently recompute those statistics from raw trace observations or replay acquisition decisions. Full new runs add evidence but use the same algorithm.'},
 {'file':'code/verify_results.py','finding':'Source identity covers sklab/*.py plus run_study.py; it excludes verify_results.py, run_all.py, analyze_results.py, tests, and protocol files. Separate manifest/command/protocol hashes remain necessary.'},
 {'file':'code/run_all.py','finding':'Runner source identity hashes code/*.py recursively, but omits tests and protocols from the resume contract; test/analysis jobs record no output artifact hashes. Consequently the runner alone is not a complete frozen evaluator or protocol boundary.'},
 {'file':'code/verify_repair.py','finding':'Exact float-derived coefficient hashes and JSON sizes are platform-sensitive and checked before numerical comparisons; hash mismatch is a real strict replay failure, not numerical disproof of the mechanism result.'},
 {'file':'code/sklab/core.py','finding':'Fixed Gaussian representation and empirical sparse selection/qualification do not model structural uncertainty or learn applicability. Guard envelope is declared; extrapolation diagnostics intentionally score outside it.'}
]
result={'schema_version':1,'bundle':'SERA_Kavi_Astra_Research_Pack_v2b','generated_utc':datetime.now(timezone.utc).isoformat(),'archive':{'path':archive.as_posix(),'sha256':sha(archive),'bytes':archive.stat().st_size},'source_root':source.as_posix(),'source_manifest_entries':parity['manifest_count'],'source_manifest_all_match':parity['manifest_all_match'],'source_pins':release['source_pins'],'identity_domains':{'experimental_posix':parity['experimental_posix_digest'],'experimental_native_windows':parity['experimental_native_digest'],'entire_code_tree_root_relative_posix':digest(code_map),'release_local_code_sha256':release['local_code_sha256'],'entire_code_tree_code_relative_posix':parity['all_code_posix_digest'],'native_orchestrator_source':states['reproduction']['contract']['source_sha256']},'protocol_digests':parity['protocol_digests'],'state_summaries':{k:{field:state[field] for field in ('status','charged_job_wall_seconds','accounting_boundary')} for k,state in states.items()},'executed_jobs':jobs,'portable_replay':json.loads((root/'portable-verification/replay.json').read_text()),'archived_repair_failure':json.loads((root/'portable-verification/repair_failure.json').read_text()),'fresh_replay':json.loads((root/'reproduction/evidence/replay.json').read_text()),'fresh_repair_replay':json.loads((root/'reproduction/evidence/repair_replay.json').read_text()),'parity_summary':{k:{'counts':v['counts'],'max_numeric_absolute_error':v['max_numeric_absolute_error'],'max_numeric_location':v['max_numeric_location'],'numeric_or_structural_failures':v['failures']} for k,v in parity['comparisons'].items()},'coverage':parity['coverage'],'raw_integrity_failures':parity['integrity_failures'],'all_records':parity['records'],'fresh_summaries':parity['recomputed_fresh_summaries'],'conditioning':json.loads((root/'independent-audit/conditioning.json').read_text()),'claims':claims,'evaluator_limitations':limitations,'full_parity_evidence':(root/'independent-audit/parity.json').as_posix(),'audit_commands':[[str(Path('D:/ai/projects/sera/.venv/Scripts/python.exe')),'-B',str(out/'audit_bundle2_parity.py')],[str(Path('D:/ai/projects/sera/.venv/Scripts/python.exe')),'-B',str(out/'diagnose_bundle2_parity.py')]],'code_identities':{p.name:sha(p) for p in [out/'audit_bundle2_parity.py',out/'diagnose_bundle2_parity.py',out/'replay_bundle2_portable.py',Path(__file__)]},'read_boundary':'Fully read Markdown reports/cookbook, handoffs, agent contract, workplan, protocols, ledgers, important model/study/verification/orchestrator/analysis source, repair and snapshot tests. All canonical raw records compared exhaustively. PDFs not visually rerendered, external paper claims not independently revalidated here, and initial defective cohort not retrained.'}
(out/'bundle2-evidence.json').write_text(json.dumps(result,indent=2))
print(json.dumps({'path':str(out/'bundle2-evidence.json'),'identity_domains':result['identity_domains'],'failures':{k:len(v['numeric_or_structural_failures']) for k,v in result['parity_summary'].items()}},indent=2))
